### ISSUE TITLE
Fileset Metadata

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/OD2#1069]
### Descriptive summary

Overview: The metadata team is fine with keeping the Hyrax out-of-the-box fileset metadata, but will need some more investigation into how the fileset metadata fields are automatically generated and mapped to the corresponding appropriate predicates.

Core fileset metadata:
Depositor
Date Uploaded
Date Modified
Fixity Check
User Activity
Characterization
(...and possibly more. Investigation needed. See related tickets below.)

Here are the characterization schemas:
[Audio](https://github.com/samvera/hydra-works/blob/master/lib/hydra/works/characterization/schema/audio_schema.rb)
[Base Work](https://github.com/samvera/hydra-works/blob/master/lib/hydra/works/characterization/schema/base_schema.rb)
[Document](https://github.com/samvera/hydra-works/blob/master/lib/hydra/works/characterization/schema/document_schema.rb) 
[Image](https://github.com/samvera/hydra-works/blob/master/lib/hydra/works/characterization/schema/image_schema.rb)
[Video](https://github.com/samvera/hydra-works/blob/master/lib/hydra/works/characterization/schema/video_schema.rb)

Currently, the fileset metadata schemas include DC, ebucore, NFO (the Nepomuk FIle Ontology), PREMIS, EXIF, and project hydra.

### Expected behavior

Filesets will have automatically generated metadata. Some of that metadata will be indexed and searchable. Fileset metadata will be documented in MAP.

### Related work

- [x] [Replace File Set & Children views to work show page #1024](https://github.com/OregonDigital/OD2/issues/1024)
- [x] [PREMIS Data indexed and accessible in exports and show pages #39](https://github.com/OregonDigital/OD2/issues/39)
- [x] [Determine fileset metadata mapping #1063](https://github.com/OregonDigital/OD2/issues/1063)
- [x] [Index fileset file format #1065](https://github.com/OregonDigital/OD2/issues/1065)
- [x] [Index fileset OCR #1066](https://github.com/OregonDigital/OD2/issues/1066)
- [x] [Make user activity private #1067](https://github.com/OregonDigital/OD2/issues/1067)
- [x] [Update MAP with fileset metadata specifications #1068](https://github.com/OregonDigital/OD2/issues/1068)

### Accessibility Concerns

Not sure.

**Comment by sseymore** [comment]
Fileset metadata has been determined and added to MAP: https://github.com/OregonDigital/OD2/issues/1307

Configuration ticket is forthcoming @wickr
