### ISSUE TITLE
Design for homepage - 70% done

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1147]
### Descriptive summary
The homepage as designed by MAC feature several functional pieces.
* A main Google-style search box with a rotating carousal of background images (curated)
* Two columns of main content
  * Featured collections (curated) with three thumbnails, the collection title, the item count, and a view all link. Ending with a view all collections link
  * About Oregon Digital with two images, a short blurb about OD, and two link blocks (First time here? and Dig Deeper) with an unordered list of links

### Expected behavior
The homepage looks and feels like the MAC design

Latest MAC design:
https://projects.invisionapp.com/share/47X400SV3BM#/screens/415938481

### Accessibility Concerns
Pay careful attention to the carousal and the WCAG requirements for a carousal to be accessible. We will need next and previous button options, and a pause function.

**Comment by straleyb** [comment]
QA:
- [ ] Image masthead is right photo (photo of blimp and people?)
- [ ] search bar background is proper color of bluish green and see through
- [ ] Oregon Digital header above search is white
- [ ] search bar has proper design based off MAC wireframes
- [ ] Featured collections displays 3 thumbnails
- [ ] Title of collection exists
- [ ] number of items exists
- [ ] view all links to collection page to see works in collection
- [ ] About oregon digital layout is right based on updates to MAC wireframe ( see #1339 )
- [ ] Images in about oregon digital are acceptable
- [ ] paragraph describing oregondigital is right with no typos

Things needing done still:

-Header still needs some overlapping fixes
-Gap in-between header and "Image Masthead" needs to be removed
-Collection title needs to be a link
-Oregon digital needs to be centered above search bar
-Collection that masthead image is from should be on the left of blue green search bar backgorund
-View all collections button needs to link to proper place.
-Anything else QA finds needs to be done.

**Comment by shieldsb** [comment]
QA fail. 

- Blue search box banner is wider on WF
- "Explorer Collections" has a yellow underline that is not part of the WF
- Search bar is longer and narrower than WF
- Under featured collections, WF has a vertical line between #of items and view all 
- Not sure that font sizes match 
- Green bar aside "view all collections" appears to have a thin black line above it 
- WF blue search bar/banner has text included (Find more than 100,000...) that is not on staging.  Not sure if that has been changed in updated WFs. 
- In the About section, "collaboration" has a typo and "comprises" should be lower case

**Comment by straleyb** [comment]
The home page is probably at 70% or so style wise. We need to check to see whether or not these problems have high priority fixes or whether or not we can punt some of these fixes down to when we refine the views the rest of the way after the major features and MVP pieces are fixed.
