### ISSUE TITLE
Move oEmbed up to the fileset level

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1316]
### Descriptive summary
Currently, oEmbed is specified as a metadata field. It makes more sense for the url to be input on the files tab and to be classified as a fileset. No derivative needs to be generated, the oEmbed embed itself needs to replace UV and any other file viewer, downloads need to be disabled/hidden.

### Expected behavior
oEmbed is a fileset
oEmbed URL is accepted in place of file uploads
oEmbed URL is accepted on the files tab
oEmbed displays instead of UV on work page if present
File uploads are not accepted if oEmbed URL is present
No file derivatives generate with oEmbed media
Downloads are not available with oEmbed media, except by the media provider

### Related work
#207 
#208 

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by CGillen** [comment]
QA:
- [ ] Create a work with minimal metadata and a regular file upload
  - [ ] It saves
  - [ ] It loads the work show page
- [ ] Create a work with minimal metadata and an oEmbed URL in the files tab
  - [ ] It saves
  - [ ] It loads the work show page
  - [ ] It loads the oEmbed player

**Comment by shieldsb** [comment]
QA pass.

**Comment by shieldsb** [comment]
The search results has a magenta rectangle as the thumbnail.  The work show page displays the actual item.

**Comment by CGillen** [comment]
Previous QA:
- [ ] Create a work with minimal metadata and a regular file upload
  - [ ] It saves
  - [ ] It loads the work show page
- [ ] Create a work with minimal metadata and an oEmbed URL in the files tab
  - [ ] It saves
  - [ ] It loads the work show page
  - [ ] It loads the oEmbed player

Additional QA:
- [ ] Create work with oEmbed URL
- [ ] Accept work through workflow at top of work show page
- [ ] Search work in search bar
- [ ] Work thumbnail is not fuchsia

**Comment by shieldsb** [comment]
QA pass.
