### ISSUE TITLE
Persist derivatives in S3

### ISSUE THREAD

**Issue by revgum** [OregonDigital/OD2#144]
### Descriptive summary

Hyrax configurations and code provides a local filesystem path for persisting derivatives to. For OD2, we want to store these in an S3 bucket where the thumbnails can be served as well as the IIIF server has access to serve full sized images.

### Expected behavior

- [ ] Make a local service to replace Hyrax::PersistDerivatives : https://github.com/samvera/hyrax/blob/master/app/services/hyrax/persist_derivatives.rb
- [ ] Add a line in the local FileSet.rb to point at the new sevice, replacing : https://github.com/samvera/hyrax/blob/master/app/models/concerns/hyrax/file_set/derivatives.rb#L45
- [ ] Thumbnails are retrieved by the downloads controller, it tries to determine if the file is a FileSet or an ID (to serve from the local filesystem). This needs to be replaced to include the ability to try (or default to) serving S3 urls (or streaming the thumbnails). https://github.com/samvera/hyrax/blob/master/app/controllers/concerns/hyrax/local_file_downloads_controller_behavior.rb

### Related work

See #141 
See #145

**Comment by revgum** [comment]
This ticket is no longer needed, related work in linked tickets.
