### ISSUE TITLE
[MVP QA] PDF / Bookreader

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1450]
### Descriptive summary

Features needed: Flip through multi-page items and pan & zoom and full-text search functionality that is indexed (OCR and serve up text file). Back-end requirement: transform PDFs into intermediary derivative OR serve up directly. Will look at Mirador for this purpose, would need to configure API calls to serve up the right stuff.

### Expected behavior

PDF 
- [x] Find or create a multi-page pdf work 
  - [x] Confirm that item can be flipped through
  - [x] Confirm that pan and zoom work throughout
- [x] Use "Search within this item" box in viewer to search for a word
  - [x] Confirm correct word is found and highlighted throughout
- [ ] Use general search bar to search for a word
  - [x] Confirm that work is returned in search results
  - [x] Confirm text snipit with first instance of word highlighted appears in work search result
  - [ ] Navigate to work and confirm correct word is found and highlighted throughout
- [ ] Use Advanced Search to search for a word
  - [x] Confirm that work is returned in search results
  - [x] Confirm text snipit with first instance of word highlighted appears in work search result
  - [ ] Navigate to work and confirm correct word is found and highlighted throughout

Repeat above for OCR'd multi-image work, plain text work, excel work, xml work, PostScript work

### Related work

#1120, #1425, #1446 

### Accessibility Concerns

Searchable text and text extraction are part of pdf accessibility requirements

**Comment by kmthorn** [comment]
@jsimic and @CGillen is this something that needs to be QA'd? This tickets was created before usability testing. We are confused by the reference to Mirador. Is this an epic ticket?

**Comment by jsimic** [comment]
@kmthorn This must have been made before we decided on UV. Yes, please QA. I just reviewed the OCR-search functionality in ticket #1938

**Comment by kmthorn** [comment]
Corey, Kate, and Chris identified this as the UV epic ticket.

**Comment by jsimic** [comment]
QA fail. Used this [https://staging.oregondigital.org/concern/documents/wd375w33s#content](https://staging.oregondigital.org/concern/documents/wd375w33s#content) for testing.

Zoom is malfunctioning. See #1423 

Searched for "august" in general search bar and work was not returned in the search results. Searched for the same in Advanced Search and work was not returned in the search results

**Comment by jsimic** [comment]
QA fail. using [https://staging.oregondigital.org/concern/documents/tx31qh70j](https://staging.oregondigital.org/concern/documents/tx31qh70j) to test.

General and Advanced search: Search on "chickpeas" returns document with first instance highlighted in search results. Highlighting does not stick after clicking to showpage. No highlighting in viewer unless using the viewer searchbox.

**Comment by CGillen** [comment]
Highlighting throughout the page will have to be an enhancement at best. There's no standard practice for word highlighting between browsers (besides `<mark>` tag, and that's going to be difficult across fields) & and pre-searching UV

**Comment by petersec** [comment]
QA fail - highlighting of search terms matched that noted by @jsimic in June 22 comment

> using https://staging.oregondigital.org/concern/documents/tx31qh70j to test.
General and Advanced search: Search on "chickpeas" returns document with first instance highlighted in search results. Highlighting does not stick after clicking to showpage. No highlighting in viewer unless using the viewer searchbox.

Same issues noted when repeating an earlier test search for 'august.'

QA pass for zoom malfunctions documented in #1423
