### ISSUE TITLE
Configuration of work types in the application

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#21]
### Descriptive summary

There are going to be very many `work types` that will be defined over the next several weeks (September 21st - November 14th). These `work types` will become objects in the application that users will pick from to create their works within Oregon Digital 2. These `work types` are defined here >>>>>>> _**INSERT LINK TO MAP HERE**_ .  We need to generate these `work types` in the application using a rake task provided by hyrax. This rake task can be found here https://github.com/samvera/hyrax#generate-a-work-type. 

You can run `rails generate hyrax:work work_type_name_found_in_map` which will generate all the files needed for the work type generated to function properly in the system. Some of the files mentioned are as such. 
```
      create  app/actors/hyrax/actors/work_actor.rb
      create  app/controllers/hyrax/works_controller.rb
      create  app/indexers/work_indexer.rb
      create  app/forms/hyrax/work_form.rb
      create  app/presenters/hyrax/work_presenter.rb
      create  app/models/work.rb
      create  app/views/hyrax/works/_work.html.erb
      insert  config/initializers/hyrax.rb
      create  config/locales/work.en.yml
      create  config/locales/work.es.yml
      create  config/locales/work.zh.yml
      create  config/locales/work.de.yml
      create  config/locales/work.fr.yml
      create  config/locales/work.it.yml
      create  config/locales/work.pt-BR.yml
      create  spec/actors/hyrax/actors/work_actor_spec.rb
      create  spec/controllers/hyrax/works_controller_spec.rb
      create  spec/features/create_work_spec.rb
      create  spec/forms/hyrax/work_form_spec.rb
      create  spec/presenters/hyrax/work_presenter_spec.rb
      create  spec/models/work_spec.rb
```

The only file that we wont need, unless heavy customizations are involved are the app/views/hyrax/works/_work.html.erb

This file should be removed to make sure that the application doesnt have too many extra files. 

There could potentially be heavy alterations of some files such as the presenters, models, and eventually, some of the indexers. Keep these in mind for future work.

As changes are made to these files, please make sure to update their specs as well.

The config/local files are used for language translation and it might be worth it to check in with these files toward the end to make sure they are sufficient for accessibility purposes. 

### Expected behavior

The expected behavior will be quite simple. You plug in the rake task in the command line and it pops out the necessary files needed to generate a work type. 

### Related work

The related work associated with this ticket will be the MAP. The MAP will need to be completed in order to generate all the necessary `work types` needed by the application. If it is only partially completed 

### Related tickets
--------------------List related tickets here-------------------------

### Steps

- [ ] Generate MAP
- [ ] Link MAP here
- [ ] create a ticket for each work type
- [ ] create ticket to configure metadata fields
- [ ] Complete generation of each `work type`
- [ ] configure specs for metadata fields
- [ ] Verify they are configured to be generated in the application and that metadata looks and behaves
- [ ] QA
- [ ] Merged

**Comment by vantuyls** [comment]
MAP: https://docs.google.com/spreadsheets/d/16xBFjmeSsaN0xQrbOpQ_jIOeFZk3ZM9kmB8CU3IhP2c/edit#gid=0

**Comment by vantuyls** [comment]
Tickets for each work type should include:
- [ ] model
- [ ] spec for model
- [ ] form
- [ ] presenter

**Comment by zhang4952** [comment]
Possible WorkTypes for OD2:
Image
Document
Audio
Video
Generic

**Comment by straleyb** [comment]
Fixed by #133 
Fixed by #129 
Fixed by #128 
Fixed by #119 
Fixed by #120

**Comment by wickr** [comment]
QA OK, we have work types created.
