### ISSUE TITLE
Easy deployment for OD2 

### ISSUE THREAD

**Issue by revgum** [OregonDigital/OD2#283]
### Descriptive summary

Tie together the pieces of infrastructure to provide the ability for hubot deployment of OD2. 

### System option

- [x] Request a beta invite to Github Actions to implement deployment there
- [ ] Stand up an instance of Jenkins X (or plain Jenkins?) and implement the deployment and configurations there

### Script option
- [x] Clone OD2-infra project to an appropriate server, this must have kubectl, docker, and all ruby dependencies to build the OD2 project
- [ ] Create a build and deployment script that automates the ansible build and k8s deployment process on the server. See #282 
- [ ] osulp/hubot : add configuration to apps.json and merge
- [ ] (prod server) deploy app : add shared/config/apps/od2.yml with configurations and ssh command line to execute the build and deployment script

**Comment by revgum** [comment]
@decimalator and I have been investigating various solutions.. (scripted, Github Actions, Jenkins X). It looks like any of these methods could tie into our hubot deployment process. 

Hubot would issue a deployment api call to GH, then I can see options from this point; 1. a webhook is tied to our deployment application which runs an arbitrary command against a target system to fire off the deployment process, 2. a webhook (from GH or Jenkins) kicks off the process of deployment using those technologies.

**Comment by revgum** [comment]
I built a Docker image that comes alive to build the OD2 image and perform a deploy. This method possible to complete, but was feeling more complicated than necessary. https://github.com/osulp/OD2-infra/tree/builder-docker-in-docker

We're waiting for Github Actions invitation, as this would be the ideal solution, or to stand up Jenkins and integrate it.

**Comment by revgum** [comment]
JenkinsX in the cloud appears to be a pretty expensive cluster to run. It might make sense to, instead, use a local VM to perform the build and deploy as a script. @decimalator?
