### ISSUE TITLE
IP Based Restrictions

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#31]
### Descriptive summary

This work includes the possible whitelisting of specific IP addresses for specific works and collections. Some collections are only accessible from the OSU or UO campuses. We would need some way of looking at a users IP address and checking to see whether they were within the proper IP range to look at specific works and collections. This has been implemented in OD but may need to be looked at again for new or alternative ways of accomplishing this. 

There are several different ways we can restrict IPs depending on how much work/engineering we want or feel is necessary. This feature is in Oregon Digital and can be found here: 

https://github.com/OregonDigital/oregondigital/commit/cca646d52f20a1e9a0796929ee5ce1342c2b339e

This expresses a more engineered version of doing IP addresses and should at least match the needs of the IP based restrictions. This may, however, be overkill, or slightly different depending on how much hyrax already supports and the changes to roles and users. If further discussion about this method is needed, then we can log that discussion in this ticket. 

Otherwise, if we simply need to reject users from specific routes, there is work that you can do in the routes based on this stackoverflow page. 

https://stackoverflow.com/questions/5553874/rails-3-whitelisting-list-of-ips-via-routes

We need to talk about requirements of IP restrictions. 

### Expected behavior

When there is a work or collection that has been restricted to "UO Only" or "OSU only" And you are on campus, you should be able to view that work. Otherwise that work should not be able to be looked at. 

### Requirements
- [ ] Admin Dashboard area to create/edit/update/delete groups of ranges for IP Restriction (UO Only, OSU Only), restricted to Admins
- [ ] Work show page should have very clear indication of IP Restriction group, such as banner or badge
- [ ] More than 1 IP Restriction group should be able to be applied to a work (both OSU and UO)
- [ ] Restricted works are not viewable in search results for those who couldn't see the work
- [ ] Can bulk assign works an IP Restriction

### Related work

Research may need to be done on technologies or gems that exist or work done in hyrax that allows for the easy whitelisting (or black listing) of IP addresses.

**Comment by jsimic** [comment]
Works not available, due to IP restriction or otherwise, should not to appear in the search results.

**Comment by wickr** [comment]
Added a Requirements section, including Julia's comment.

**Comment by jsimic** [comment]
POSM reviewed. Closed.
