### ISSUE TITLE
install triplestore

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#33]
### Descriptive summary

We have chosen blazegraph

### How To Install Blazegraph and triplestore-adapter

This PR in scholars archive configures blazegraph and uses the triplestore-adapter, which allows the ability to access triplestores like blazegraph. A bit of work will have to be done early on the get this functioning. 

https://github.com/osulp/Scholars-Archive/pull/564/files

This will get OD most of the way there, with a little wiggling of files into place to get it all flowing naturally. A good way to test this is enable a field to be controlled and add it to the supporting files for the triplestore. Then use a uri from id.loc.gov and put that into the form. If the form accepts it and displays a label, it is working properly. Otherwise exceptions will be raised and more work will have to be done on this. 

### Expected behavior

- [x] Install blazegraph and copy over configuration files for blazegraph
       * We know this is working, because you should be able to run the triplestore adapters rake task 
          and it works.
- [x] Setup Triplestore adapter objects in OD2 to connect to the triplestore adapter interface and test.
       * We know this is working because the tests pass
- [x] Configure GenericWork to have a triple powered field.
       * You can input a URI and it can grab the label and index it, displays the label on the show page.

**Comment by revgum** [comment]
Discussion this morning verified that we intend on using Blazegraph and the triplestore-adapter integration much like ScholarsArchive.

**Comment by revgum** [comment]
Blazegraph has been added to the development environment, and now needs to be included in staging/production kubernetes in the OD2 infrastructure repository.

**Comment by revgum** [comment]
Blazegraph added and deployed to staging and production
