### ISSUE TITLE
[10] Design for Collections Landing Pages

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#43]
### Descriptive summary

This may or may not be work done in hyrax. There should be the ability to express a collection landing page per collection. This landing page would contain information about the collection. Whats in it? Where did it come from? What is its significance? Some sort of description of the collection. It should also have representative images associated with the collection. ~These should be displayed on the landing page in a carousel like rotation.~ These should be displayed in a single row of thumbnails, 4 across.

These have already been implemented in OD and are a very important piece of displaying a collection for users to see. This collection landing page needs to be accessible from a list of collections somewhere in OD2. 

### Expected behavior

When the collection is visited, all the information associated with the collection will be displayed on its landing page.

Latest MAC design:
https://projects.invisionapp.com/share/47X400SV3BM#/screens/415938473

###Related Issues
#42

**Comment by mccallum** [comment]
https://sketch.cloud/s/mEz3z/Qbpokae

**Comment by vantuyls** [comment]
@petersec @jsimic @wickr and everyone - can folks put some eyes on the collection showpage work for feedback? 

@mccallum do you think this is ready to implement or is this still in progress?

**Comment by jsimic** [comment]
I'm concerned that the text, including Browse and Advanced, disappear against the banner. Is the banner static or a slideshow like OD1? Can we split the banner?

**Comment by vantuyls** [comment]
@mccallum can you take those feedbacks into account for some revisions?

**Comment by wickr** [comment]
Is there an option of using the OSU logo and wordmark in their horizontal orientation within the logo spot? Like whats on oregonstate.edu but without the full width orange bar. There's a lot of vertical space used in the current sketch.

What about Collections that have supporting pages, where are links to those going? Below 'Browse/Advanced' ?

I don't like that the Collection Search box is larger than the Collection Title. Also no indication or prompt of what exactly that is.

Are long Collection Titles going to wrap in that column?

Latest Items is fine, but some Collections will still need the Carousel or other similar way to feature highlighted items.

What to things in Latest Items look like when Documents or other items and not the standard photo landscape layout?

**Comment by mccallum** [comment]
@vantuyls Certainly. I'm not content with it. Franny, Ray, and I are meeting Thursday for some role/responsibility clarification and refinement to align yearly job objectives with OD2, along with a spot of spirit elevation for me. :) Might make a little presentation in PMOP after that.

**Comment by wickr** [comment]
Also are we not having Facets on these pages?

**Comment by CGillen** [comment]
Updated with link to latest MAC design. Likely changes will be minor or none at all.

**Comment by straleyb** [comment]
QA:
- [ ] Description of collection should be in the right spot at top of page and in the proper font
- [ ] social media buttons should be under temporary image 
- [ ] If more than 4 items in collection exist, it should display only 4
- [ ] Hover over on pictures should display title
- [ ] Bottom section should exist (two horizontal lime green lines with buttons and a temporary search area)

**Comment by shieldsb** [comment]
QA fail. 

General Notes: 
- there is no text displayed for collections descriptions
- top right where the university logo displays on the wireframes is just a fuchsia box, sometimes it overlaps with the social media buttons 
- hovering over images does not display their titles 
- fonts throughout page do not match wireframes 
- size of images is not always consistent and does not match wireframes, see issues specific to collections/file types below 
- bottom search section spacing does not match wireframes, though the full search features have not yet been added and may resolve this issue 
- there is a --> at the bottom of the page for each collection 

Collection specific notes:
**Baseball Centennial** - of the four images, one is for an audio file and the icon for it displays incorrectly (see screenshot below) 
**Dan Powell photographs** - fuchsia block causes break in collection title line with the # of items text being split onto two lines (see screenshot below) 
**University of Oregon Special Collections Manuscripts and Rare Books** - three icons in place of images display incorrectly (centered, too large, overlap) (see screenshot below) 
**Reuniting Finley and Bohlman** - the four images are for video files and they overlap each other (see screenshot below) 
**Historical Maps of Oregon State University** - third map image has a grey bar under it (see screenshot below) 

![image](https://user-images.githubusercontent.com/53542788/92755937-2d7fde80-f341-11ea-891d-ee201a47fec4.png)
![image](https://user-images.githubusercontent.com/53542788/92756047-4b4d4380-f341-11ea-8b3b-32f27933008b.png)
![image](https://user-images.githubusercontent.com/53542788/92756170-6cae2f80-f341-11ea-9b1a-6b4b8e7400e2.png)
![image](https://user-images.githubusercontent.com/53542788/92756230-7f286900-f341-11ea-9bf2-6b65d1513d3e.png)
![image](https://user-images.githubusercontent.com/53542788/92756298-91a2a280-f341-11ea-95bb-d9476ca1a041.png)

**Comment by CGillen** [comment]
Previous QA:
- [ ] Description of collection should be in the right spot at top of page and in the proper font
- [ ] social media buttons should be under temporary image 
- [ ] If more than 4 items in collection exist, it should display only 4
- [ ] Hover over on pictures should display title
- [ ] Bottom section should exist (two horizontal lime green lines with buttons and a temporary search area)

Continued QA:
- [ ] Search section should search within collection
- [ ] Search button between green lines and magnify glass near search box should both work identically
- [ ] Several 'View all' buttons exist in correct places and links to a default search of the collection
- [ ] Individual works link to themselves
- [ ] Work hover does not cause format jumping or issues

**Comment by shieldsb** [comment]
This ticket is close to passing.  Just a few items for your review first. 

The collection title text is too large and does not match the wireframe (text also looks bolded in the wireframe). 
- The number of items in the collection and the view should not have a line break after the title- based on the wireframe.  
- There is a grey bar under the collection description.  The space under that bar has extra white space between it and the images. Currently the collections page has two search boxes displaying.  The one in the header and the one I used to find the collection. 
-  The view all button at the bottom: text seems slightly larger than the wireframe.

**Comment by shieldsb** [comment]
QA pass.
