### ISSUE TITLE
Discoverable Compound Objects

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#46]
### Descriptive summary

Compound Objects exist in Hyrax by virtue of the work done with PCDM. Then Hyrax was extended to be able to track these compound objects. These compound objects come in many forms. One way it manifests is through a work and its image associated with it. That image is a FileSet object which is nested under the work. FileSets are discoverable by themselves but also from a work with a related FileSet. This was extended even further to be able to support Parent/Child relationships within the system. A parent work could be an article, but a child work associated with that article could be an existing dataset used in the article. That dataset could be a work itself with many different pieces of metadata associated with it. 

We need to make this relationship more visible to people trying to discover works. Currently, when a search is fired off, works show up in a list format. These works do not show users whether or not that work has children works, filesets, or anything else. It would be useful for users to see maybe if this work was contained in a collection or many collections. Whether or not it is a parent or has a parent. And many other different ways. 

Some questions that arise are, how far "up" or "down" do we want to display in the hierarchy. We dont want to go too bananas on it, but we also want to provide enough information to help users who are trying to discover and research. 

This spills into the idea, that maybe we need to overhaul the search result interface, to display many different types of results in different sections. This is definitely an epic ticket that needs more discussion but should serve as a good starting point to figure out the work involved and needed.

### Expected behavior

When a user searches for a work, you get contextual information about its relationship to other objects. Parents? Children? In a collection?

One example, if it's possible to do this (Duke's new ArcLight): https://archives.lib.duke.edu/?utf8=%E2%9C%93&group=true&search_field=all_fields&q=duke

### Related work

Some work may be done in collection extensions that would serve to help support this idea and could be done by others at the point of working on this ticket.

**Comment by vantuyls** [comment]
@mccallum another mockup request. this is specifically for the search results page. we need to be able to:
- [ ] see, in a search result, some contextual information about parent-child relationships
- [ ] be able to determine whether a result is a collection or a work
- [ ] if a work is found in a collection, contextualize the search result so that it is apparent that the work was found in the collection

there are probably other considerations here. happy to discuss. 

cc @jsimic @petersec

**Comment by raybrarian** [comment]
Meeting planned with Features/Metadata/Service Managers to discuss options.

**Comment by CGillen** [comment]
Looks like blacklight supports results collapsing and grouping: https://github.com/projectblacklight/blacklight/wiki/Configuration---Results-View#advanced-result-collapsing--grouping
Not sure what the configuration looks like and not sure what Blacklight would do with it when it goes to render the search results but it has configuration for it.

**Comment by CGillen** [comment]
```
    config.index.group = 'visibility_ssi'

    config.default_solr_params[:group] = true
    config.default_solr_params[:'group.field'] = 'visibility_ssi'
    config.default_solr_params[:'group.limit'] = 500
    config.default_solr_params[:'group.ngroups'] = true
```

I found the configuration to get blacklight to group results. It's completely undocumented from the blacklight side, luckily Solr is very well documented.
`config.index.group = 'visibility_ssi'` may be unnecessary, not really sure at this point.

The big take home though, is you'll notice I used 'visibility_ssi' in my example. You can only group on fields that are single value. Almost all of our fields are multivalue, and grouping on collections would require works be in at most one collection as a system-wide requirement. We could provide works with a way to specify "grouping collection" and that be the collection they group in search results, this may also be needed for a "primary collection" mechanism if we wanted to do some displaying on the work show page or something.

**Comment by CGillen** [comment]
Huge problem! doing this made it look like issues were scattered EVERYWHERE in Hyrax. I opened #1251 because of it and there were plenty other things I was going to work on during Samvera PNW. This grouping functionality practically broke everything about Hyrax related to works.

It's POSSIBLE we could do it without introducing that breakage. I'll explore more if we think this is still necessary.

**Comment by jsimic** [comment]
@CGillen Drafts of compound objects in line with MAC wireframes: [compoundObjects_finalDrafts folder](https://drive.google.com/drive/u/1/folders/1c4mylcxJtsEODlcC1hCcDIeaWc3QNQB2) 
Includes display of parent and child objects in list and grid view search results, and item view pages for parents and children.
