### ISSUE TITLE
Bulk Work (Ingest, Review, Edit, Export, Task Control)

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#48]
### Descriptive summary

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! IMPORTANT !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

THIS WORK MAY BE CONTRACTED OUT AND NEEDS MAJOR DISCUSSION ON WHAT THE NEEDS OF THIS FEATURE ARE!!!!!!

-Bulk Edit
-Bulk Review
-Bulk Ingest
-Bulk Export
-Bulk Task Control

### Steps to reproduce the behavior

1. Do this
2. Then do this...

### Related work

Link to related tickets or prior related work here.

**Comment by vantuyls** [comment]
We have the go-ahead to start discussions about this. @jsimic and i will be meeting with Avalon and Hyku parties to hammer out the details of what this looks like. To my view, MVP looks like:
- [ ] ingest of works and metadata via a few formats (csv, bag, json?)
- [ ] export of works and/or metadata via a few formats (csv, bag, json?)
- [ ] update work metadata and/or files via bulk ingest in a few formats (see above)
user interface in dashboard that allows one to:
- [ ] take the above mentioned actions via UI
- [ ] view the status of the above ingest/export jobs including some/all steps of processing the works
- [ ] ability to restart failed ingest at the work level or the entire job level (??)
- [ ] ability to cancel an ingest or export
- [ ] user friendly error reporting to help decipher why jobs failed or succeeded
- [ ] notification of job status via notifications panel and/or email to specified users

**Comment by jsimic** [comment]
POSM reviewed. Closed. Covered in grant application
