### ISSUE TITLE
Collection Edit page should include Configure Facets tab

### ISSUE THREAD

**Issue by vantuyls** [OregonDigital/OD2#528]
### Descriptive summary
IF Configurable Facets is selected for this collection type, the collection edit screen should include a new tab labelled "Configure Facets". This tab will take the user to a screen that allows for the following abilities:
- [x] turn facets on or off for this collection
- [x] change the order of the facets for this collection
- [x] edit the label of a facet for this collection

The above configuration of facets in a collection should only appear for this collection.  

### Related work
#527 

### Accessibility Concerns

- navigation and selection of elements on the page

**Comment by CGillen** [comment]
Closed by:
#531 #532 #533 #547 #550 #551

**Comment by vantuyls** [comment]
qa pass - facets page appears
