### ISSUE TITLE
Facetable option on collection type dashboard displaced other options

### ISSUE THREAD

**Issue by vantuyls** [OregonDigital/OD2#571]
### Descriptive summary

addding the Facet Configurable option to the Collection Type edit menus has generated the following issues:

- [ ] all of the text has been somewhat displaced so that it is no longer in line
- [ ] the Apply To New Works checkbox is now under Facet Configurable, but that box is a subselection for the Sharing option and should be placed after Sharing (still indented)
- [ ] text for Facet Configurable should follow the style of the rest of the options on this page - all capitals for the name of the option and normal case for the description of the option

**Comment by vantuyls** [comment]
<img width="927" alt="Screen Shot 2019-06-12 at 1 39 23 PM" src="https://user-images.githubusercontent.com/9534576/59385535-6fbf0800-8d19-11e9-825d-419fad7a7b34.png">

**Comment by CGillen** [comment]
QA
- [ ] Collection items are placed to your liking
- [ ] `FACET CONFIGURABLE` is capitalized
- [ ] `FACET CONFIGURABLE` does not break up the `SHARING`-`APPLY TO NEW WORKS` relationship

**Comment by vantuyls** [comment]
QA Pass
