### ISSUE TITLE
Work Show Page: MyShelf functionality

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#643]
### Descriptive summary

#604 Added a button for users to add works to a section called "MyShelf." This is meant to be a collection-like feature that allows users to gather materials and present or share them to others in aid of instruction.

### Expected behavior

- ~One user should have one shelf~ One user can have many shelves (collections)
- Each shelf should be shareable via a single link (Using browser URL)
- Authenticated and unauthenticated users should see the whole shelf OR the items they have access too, whichever is easier/free
- Individual items may be restricted with ~IP,~ Role, or On-Campus rules
- When adding a potentially restricted item, the user should be alerted of the restriction
- When adding an item as an unauthenticated user, the user should be directed to login first, then ~the item should be added automatically after login~ back to the item page to add again

- [x] User can create a collection of collection type User Collection (#1143)
- [x] User has an interface to create a collection (#1144)
- [x] User can add a single work to a collection from the work show page (#1144)
- [x] User can add many works to a collection from the search results page (#1144)
- [x] User can browse and interact with their collections (#1145)
- [x] User can export items from a collection to zip (#1146)

### Related work

#604 

### Accessibility Concerns

Unknown at this time

**Comment by straleyb** [comment]
Dependent on roles and permissions

**Comment by wickr** [comment]
This was intended to be built on Hyrax User Collections with re-branding and tweaks.

**Comment by CGillen** [comment]
Most of the work is done. We'll deal with new problems as new tickets.
