### ISSUE TITLE
Work Show Page: Attach download functionality to work download links

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#669]
### Descriptive summary
Combine the work from #644 and #615. The download section should become a singular box without iteration per asset. We should feel safe removing action links for individual assets.

### Expected behavior
Work show page download links should download the temporary files from #666 and #668

### Related work
Child of #644 
Relies on #666, #668 

### Accessibility Concerns
None

**Comment by CGillen** [comment]
QA:
- [ ] Work show pages have two download links
- [ ] Files + Metadata (ZIP) provides a zip file with all latest files (images) and metadata as CSV (#668)
- [ ] Metadata Only (CSV) provides a CSV file with only metadata. This matches above CSV (#666)
- [ ] Metadata fields that are exported are appropriate and expected (#666)

**Comment by raybrarian** [comment]
@CGillen - is expected behavior that the download function is not available for non-authenticated users? When I'm not logged in, download links prompt me to login at the sign-in landing page: http://staging.oregondigital.org/users/sign_in?locale=en

@sseymore, @wickr, @carakey - could one of you take a look at the exported metadata fields and confirm they are being created in the csv as expected?

**Comment by CGillen** [comment]
@raybrarian & @shieldsb (from #644) I'm going to look at why and how permissions are happening and I'll document here for our permissions sprint.
For now, I don't think it really matters what the default behavior is, as long as someone can download, since we're going to overhaul access later.

**Comment by sseymore** [comment]
QA pass for Metadata fields that are exported are appropriate and expected
