### ISSUE TITLE
Expand abilities to include actions from spreadsheet and implement throughout OD2

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#695]
### Descriptive summary

Spreadsheet with roles and actions found here: https://docs.google.com/spreadsheets/d/1-Mk0CUBU3guGLDDFyuS2l6rIku5eZjnNVDMxH9HuqoM/edit#gid=0

The left most column of the spreadsheet lists the actions that can be taken in the system. These actions need to be translated into abilities in the Ability.rb file. We may want to organize them more by creating 'themed' behaviors surrounding different pieces like "works" "collections" etc. 

These abilities will look at IP ranges and roles associated with a specific user and make decisions based on whether or not that user within the specific ip range and role can do a specific action. 

There will be a lot of work finding all the places these abilities need to be set in and verified. 

- [x] Translate spreadsheet into Abilities "actions"
- [ ] Verify that "actions" are returning the right result on a per role basis
- [ ] Expand OD2 to utilize new "actions" to allow users to do certain things in the system
~Whitelist/Blacklist IP ranges~
~Expand "actions" to utilize IP ranges to further enhance the permissions functionality~

### Expected behavior

The expected behavior of this feature is "when a user has a specific Role/IP in the system and chooses to do an action found in the spreadsheet, the user should be allowed/disallowed to do that action based on their role/IP"

### Current Behavior

A user can either be an admin or non admin.

### NOTE

Eventually we may want to expand this to a "Per collection" grouping as well, which we may want to keep in mind while expanding this feature set.

Syntax:
`if can? :show, @presenter` will be a common one we use.

### Documentation
https://github.com/CanCanCommunity/cancancan
Cancancan documentation

**Comment by CGillen** [comment]
Find other permissions tickets and link here. This ticket is for looking at the spreadsheet again and reviewing that those have not been broken again.

**Comment by CGillen** [comment]
@thornka This is the biggest ticket for this workcycle. Before you begin any work here, I want you to review the permissions matrix, create some test users that match the user profiles, and find what we have broken over the course of development. For the first bit of the WC I'll be out, so lean on @straleyb for information about what this all means, or wait until the second week.

This is a tangled hairball of a ticket and implementation so take your time with it. If you get nothing else besides auditing the matrix that will take us a LOOOONG way towards MVP

**Comment by CGillen** [comment]
@thornka  Reviewed this during WC19. She found this to still be working as intended. I still want this QA'd continuously and top-to-bottom before launch

**Comment by shieldsb** [comment]
Depositors can create an OAI set in the dashboard under "new collection" 
Collection Curator (without manager role) can view private works, but can not view items set to UO or OSU

**Comment by CGillen** [comment]
QA:
On production:
- [ ] As a depositor, I can not create an OAI set
- [ ] As a Collection curator or admin, I can create an OAI set

On staging:

- [ ] As a CC, I can view a private, OSU and UO work

**Comment by shieldsb** [comment]
QA pass.
