### ISSUE TITLE
WC7 - Setup on-premises k8s cluster

### ISSUE THREAD

**Issue by decimalator** [OregonDigital/OD2#752]
During WC7 we need to build out the new on-premises staging environment at OSU.

- [x] Setup control plane and worker VMs
- [x] Setup Kubernetes cluster
- [x] Integrate with OSULP Rancher
- [x] Update CI/CD build/deploy pipeline
- [x] Provision storage
- [x] Test OD2 in new staging environment

**lib-odcp1-3** (control plane nodes)
- 4 CPU
- 8GB RAM
- 100GB disk

**lib-odwork1-4** (worker nodes)
- 4 CPU
- 24GB RAM
- 100GB disk

**32 TB NFS Volume** (high capacity asset/derivative storage)

**Comment by decimalator** [comment]
Christa and I got the VMs deployed to run the cluster
We spun up the initial K8S cluster on top of the 7 nodes (3 CPs, 4 workers)
We've integrated it with our local Rancher system

**Comment by decimalator** [comment]
I've updated the CircleCI config to also build a container image and push it into our local Beavernetes Container Registry on the same merge to `master` mechanism we've been using while developing on AWS. I've left the ECR image push in place so devs will be able to continue testing against the AWS staging environment while we get it fully working on-prem.

`⇨ curl -s https://registry.library.oregonstate.edu/v2/od2_web/tags/list
{"name":"od2_web","tags":["20190924230041-WC3-0.0.1-a091ed2"]}`

**Comment by decimalator** [comment]
The new environment seems to be working thus far. I got the `web` pod running and ran a `rake db:migrate` to get a bare database initialized.

**Comment by decimalator** [comment]
Storage has been provisioned by IS

10.192.164.4:/lib_od2

I've added all of our worker nodes to our VLAN 864 so that the worker nodes can access the storage network. If we add any workers that for whatever reason can't be connected to 864 we'll need to add node taints to prevent nodes NOT on 864 from trying to run containers that require NFS storage

**Comment by decimalator** [comment]
Our production storage is the `od2-data` volume, with apps currently configured to use the temporary volumes `nfs-branding` and `nfs-uploads`

```
NAME            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
blazegraph      Bound    pvc-b812b76e-de4a-11e9-b0bb-005056865b1e   50Gi       RWO            longhorn       7d1h
db              Bound    pvc-163d321f-e3b6-11e9-b0bb-005056865b1e   10Gi       RWO            longhorn       4h
fcrepo          Bound    pvc-bfd520a9-de4a-11e9-b0bb-005056865b1e   100Gi      RWO            longhorn       7d1h
nfs-branding    Bound    od2-branding                               1740Gi     RWX                           4h23m
nfs-uploads     Bound    od2-uploads                                1740Gi     RWX                           4h22m
od2-data        Bound    od2-data                                   32Ti       RWX                           4h22m
redis           Bound    pvc-da2b4e22-e3b5-11e9-b0bb-005056865b1e   10Gi       RWO            longhorn       4h2m
solr            Bound    pvc-4637fba4-dfc7-11e9-b0bb-005056865b1e   50Gi       RWO            longhorn       5d4h
solr-zoo-data   Bound    pvc-47dbd49b-dfc7-11e9-b0bb-005056865b1e   50Gi       RWO            longhorn       5d4h
```
